### ISSUE TITLE
Inconsistent PBSTREAM with the input PGM

### ISSUE THREAD

**Issue by oschan77** [MigVega/Ogm2Pgbm#11]
Hello, thank you for your work on this project. @MigVega 

I am experiencing an issue with the conversion process from PGM to PBSTREAM. Specifically, the map of the output PBSTREAM is **inconsistent** with the PGM I provided. I wonder why and how can I solve this. Thanks!

Input PGM:
![Screenshot from 2024-06-20 11-15-32](https://github.com/MigVega/Ogm2Pgbm/assets/95953478/8fed0ee4-b159-46b9-862a-4213a1c3cfc6)

Map in PBSTREAM after conversion:
![temi](https://github.com/MigVega/Ogm2Pgbm/assets/95953478/f20a16f4-4948-4efc-a8e8-9746ca944dd8)

yaml file:
```
image: slam_state.pgm
resolution: 0.025
origin: [0.0, 0.0, 0.0]
negate: 0
occupied_thresh: 0.40
free_thresh: 0.20
```

**Comment by MigVega** [comment]
Hi @oschan77,

The result looks very different.
I believe the issue should be with the resolution of the pgm image, I would first increase it and try one more time.

Let me know if it works!

**Comment by oschan77** [comment]
It works! Thank you so much for your help. This project helps me a lot.

**Comment by MigVega** [comment]
It's great to know that it helps you reach your goals! 
Please remember to cite the code and the paper if you are writing academic work with it.
