### ISSUE TITLE
cartographer offline map error

### ISSUE THREAD

**Issue by wowowolala** [MigVega/Ogm2Pgbm#2]
hi, when I followed the document to convert map.pgm to map.pbstream , I got a error.
I typed this command " roslaunch cartographer_ros ogm2pgbm_my_robot.launch bag_filename:=/root/.ros/ogm2pgbm_sensordata.bag "
This is my error below.

![cartographer_error](https://user-images.githubusercontent.com/52536996/215432095-9f13e536-9193-4b17-b261-b0702c3014c8.png)

**Comment by snakehaihai** [comment]
i have no issue in running this. did you source the correct place to use the provided cartographer?
![image](https://user-images.githubusercontent.com/6070995/215471657-62e01ffe-b5d9-41ee-8daa-9ef85e008aba.png)

**Comment by MigVega** [comment]
I also can not reproduce this error.
Are you using docker or not?
To launch Cartographer you need to have it installed and sourced as @snakehaihai commented.
