### ISSUE TITLE
docker instructions

### ISSUE THREAD

**Issue by tugbakara** [MigVega/Ogm2Pgbm#3]
Hi, I want to use docker with this reo but I never use it before that's why I have a look installation docker into my Nvidia etson but then do I need to run dockerfile in the main folder only? I dont know what to do actually? Do I have to install ubuntu ros etc into docker? Also Nvidia serves docker files for ROS.

**Comment by MigVega** [comment]
Hi,
Yes, you only need to build the container in your Jetson.
Following this steps: https://github.com/MigVega/Ogm2Pgbm#step-by-step
Let me know if it works otherwise you can also add your problem with a complete description, perhaps I can help :smile:

**Comment by tugbakara** [comment]
Thanks, if I face a problem I will provide here. :)
