### ISSUE TITLE
Dockerfile issue

### ISSUE THREAD

**Issue by tugbakara** [MigVega/Ogm2Pgbm#4]
Hi, when I check the Docker exists or not I saw Docker comes dafult with Nvidia Jetson series, then I just attempt to  run your Dockerfile but it gives me error like:
```

exec /bin/sh: exec format error
The command '/bin/sh -c true 	&& echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc 	&& echo "source $ck_dir/devel_isolated/setup.bash" >> ~/.bashrc         && mkdir -p $ck_dir' returned a non-zero code: 1
Unable to find image 'carto-test:latest' locally
docker: Error response from daemon: pull access denied for carto-test, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```
When I searched about the exec error I gotsome ideas to solve it but none of them worked.
Also, from the error there is not carto-test image? Do I need to create it?

**Comment by oschan77** [comment]
@tugbakara I am facing the same issue. Did you solve the problem? Thanks.

**Comment by tugbakara** [comment]
sorry, I am not using this package no longer.
