### ISSUE TITLE
bag file importance

### ISSUE THREAD

**Issue by tugbakara** [MigVega/Ogm2Pgbm#6]
Hi @MigVega , I want to use your package with my real robot but in the codes you run bag files, can I run these codes w/o bag files or do I need them ? Does using robot with bag file support odom correction?

**Comment by MigVega** [comment]
Hi, sorry for the late reply.
The bag file is an intermediate generated file that is used to save the simulated laser information, which is then input into a trajectory builder (either Cartographer or SLAM toolbox).
So yes, you can run the code without a bag file; you only need a PGM file with the corresponding YAML.
